### PR TITLE
https.globalAgent added to fetcher to support proxies

### PR DESCRIPTION
**Pull request by garrylachman**
https.globalAgent added to fetcher to support proxies

### CODE REVIEW

**Comment by sebinsua** [comment]
Published. Let me know if there are any issues.

**Comment by garrylachman** [comment]
I think isomorphic-fetch need to be replaced. its old & not maintained

**Comment by sebinsua** [comment]
With what though?

**Comment by garrylachman** [comment]
node-request or node-fetch which isomorphic-fetch based on

**Pull request merged**
